---
abstract: 'what attribute triggered me?'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::Moose: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.015, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-WhatTheTrig
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  MooseX::WhatTheTrig:
    file: lib/MooseX/WhatTheTrig.pm
    version: 0.001
  MooseX::WhatTheTrig::Trait::Application:
    file: lib/MooseX/WhatTheTrig.pm
    version: 0.001
  MooseX::WhatTheTrig::Trait::ApplicationToClass:
    file: lib/MooseX/WhatTheTrig.pm
    version: 0.001
  MooseX::WhatTheTrig::Trait::ApplicationToRole:
    file: lib/MooseX/WhatTheTrig.pm
    version: 0.001
  MooseX::WhatTheTrig::Trait::Attribute:
    file: lib/MooseX/WhatTheTrig.pm
    version: 0.001
  MooseX::WhatTheTrig::Trait::Class:
    file: lib/MooseX/WhatTheTrig.pm
    version: 0.001
  MooseX::WhatTheTrig::Trait::Package:
    file: lib/MooseX/WhatTheTrig.pm
    version: 0.001
  MooseX::WhatTheTrig::Trait::Role:
    file: lib/MooseX/WhatTheTrig.pm
    version: 0.001
requires:
  Moose: 2.0600
  Scope::Guard: 0
  perl: 5.008008
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/MooseX-WhatTheTrig/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooseX-WhatTheTrig
  homepage: https://metacpan.org/release/MooseX-WhatTheTrig
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-moosex-whatthetrig.git
version: 0.001
